#!/usr/bin/python3.7
# a place to put your lists of accounts, etc.

class Inputs(object):

    x = ['TTSETeCA3FWQ3Y32TCFEwJvzqGbxiXNxtkzPb3z']

    inputlist = ['TTbKRT4vrHMQdyQCATrdu6godeo1FJWSFVVk']

    x = ['TTbKRT4ooR8Yb4VgRRitEpDt74qGzo7cNVnQ']

    xferlist = ['TTbKRT4nxYfyWgATiHh3dZBrpFe2osT6H21B',
                'TTbKRT4o2Wm5aejgdV3pxC2jVYw5DzGsFzj5',
                'TTbKRT4oNGc58s1K6zw3AUbcfJr9V7SU3WKv',
                'TTbKRT4qYZtALN5vZGHbbNToqTzSTcMJpapL',
                'TTbKRT4riVan8h5hRJevzt9bJ11FSKuDVGiU',
                'TTbKRT4sddAQ9j3fVvmvneFA32k1yzfsvC4p',
                'TTbKRT4sEkWV71GG1D2kTTELyKVrYU3r8J5e',
                'TTbKRT4taQHeh9XrH7WhzVDu5UM5S2cMEguR',
                'TTbKRT4tXjJHA9dURtPCDRDfgyQrbdhrmxsy',
                'TTbKRT4u1cND3XGYg6F2KxACcg6e3uewwJ2y',
                'TTbKRT4u1KQY4ZUs4qQUetq6mQgTXmTB3Yhh',
                'TTbKRT4uQxympsoeAZJaadgH8G6CoapZAzG6',
                'TTbKRT4vzTPhYDqdXCCDJuXUKvPNoTjFqXJm',
                'TTbKRT4wkUjLYmWeT4faSPWxYdBGtt41AcM3',
                'TTbKRT4xBpnSBEvVqvbbRRXjPEBAkKnL2XGS',
                'TTbKRT4o2PPpu3xuKLWCbY1Y6mbmNPB6Gxst',
                'TTbKRT4oqYmhia4jG8kbBjGzS5Skx59Q94ej',
                'TTbKRT4vMkq94SLRCZFgRQpQ252SejJQnZrR',
                'TTbKRT4hTEmtvqcsh6KujDc7ndB4Y3TcPkbY']

    # orig_accts1 = ['TTbKRT4nxYfyWgATiHh3dZBrpFe2osT6H21B',
    #             'TTbKRT4o2Wm5aejgdV3pxC2jVYw5DzGsFzj5',
    #             'TTbKRT4oNGc58s1K6zw3AUbcfJr9V7SU3WKv',
    #             'TTbKRT4ooR8Yb4VgRRitEpDt74qGzo7cNVnQ',
    #             'TTbKRT4qYZtALN5vZGHbbNToqTzSTcMJpapL',
    #             'TTbKRT4riVan8h5hRJevzt9bJ11FSKuDVGiU',
    #             'TTbKRT4sddAQ9j3fVvmvneFA32k1yzfsvC4p',
    #             'TTbKRT4sEkWV71GG1D2kTTELyKVrYU3r8J5e',
    #             'TTbKRT4taQHeh9XrH7WhzVDu5UM5S2cMEguR',
    #             'TTbKRT4tXjJHA9dURtPCDRDfgyQrbdhrmxsy',
    #             'TTbKRT4u1cND3XGYg6F2KxACcg6e3uewwJ2y',
    #             'TTbKRT4u1KQY4ZUs4qQUetq6mQgTXmTB3Yhh',
    #             'TTbKRT4uQxympsoeAZJaadgH8G6CoapZAzG6',
    #             'TTbKRT4vzTPhYDqdXCCDJuXUKvPNoTjFqXJm',
    #             'TTbKRT4wkUjLYmWeT4faSPWxYdBGtt41AcM3',
    #             'TTbKRT4xBpnSBEvVqvbbRRXjPEBAkKnL2XGS',
    #             'TTbKRT4o2PPpu3xuKLWCbY1Y6mbmNPB6Gxst',
    #             'TTbKRT4oqYmhia4jG8kbBjGzS5Skx59Q94ej',
    #             'TTbKRT4vMkq94SLRCZFgRQpQ252SejJQnZrR',
    #             'TTbKRT4hTEmtvqcsh6KujDc7ndB4Y3TcPkbY']


    #     cklist = ['TTbKRT4gdnX68zo6NMzt1YoEtcdKUkpdA8SC',
    #                    'TTbKRT4h2HMcNMRgWgVxAXzWytSjY5ixrhFW',
    #                    'TTbKRT4hhemTmsv6w9ykeupD6zwu3rC8vpyh',
    #                    'TTbKRT4iYyndPE7ecCjQKnvaiiUSdiYCXR5E',
    #                    'TTbKRT4kqbSDDSXL2VSE9hvzPoisvKnBoRSz',
    #                    'TTbKRT4mcFGWvCgMwprNVCifkNwgGP7Q2UAv',
    #                    'TTbKRT4mdzsc9dbvMS8N8UUJTCsoxCZTQGue',
    #                    'TTbKRT4mEF6eWHwxUYKaB7qQPuLTGvxWaM6A',
    #                    'TTbKRT4pgb9hUW4JERiuePBSCZNh8zrVQu5o',
    #                    'TTbKRT4rL5dnhRJyYz39VcoftcUDBti9Qrni',
    #                    'TTbKRT4rUxUMvyuBsbfS9PmoHqVJ8EhcRwzD',
    #                    'TTbKRT4rY7bDtZyciJF7dxgsbFzXw7opRzVx',
    #                    'TTbKRT4sYGMwUfocG6qywkoZQMV1dsDbj3JM',
    #                    'TTbKRT4tkrYaRAeQcktSQ5k5voUb35f71feA',
    #                    'TTbKRT4tTAWzAVbsaUwMGqtJnRm2ww6A9U1H',
    #                    'TTbKRT4uidQUHXSAtmNayckjF1pXYyx45M89',
    #                    'TTbKRT4v36STBfA5qA9AHXJfh2i1rtMiN8Xj',
    #                    'TTbKRT4wBXBY4PDqpv4k2Z6cSMR4Lw8R8KsS',
    #                    'TTbKRT4wiwW5EyB5MEhwnv5UoqtkPGoBCmeR',
    #                    'TTbKRT4x17qjDfAZpQwEBNcf7nsccUgs4Vzv',
    #                    'TTbKRT4xMGnUcezcWAjQkHSFUdjrkgxnKZdX']


    inputlistx2 = ['TTbKRT4gdnX68zo6NMzt1YoEtcdKUkpdA8SC',
                 'TTbKRT4h2HMcNMRgWgVxAXzWytSjY5ixrhFW',
                 'TTbKRT4hhemTmsv6w9ykeupD6zwu3rC8vpyh',
                 'TTbKRT4iYyndPE7ecCjQKnvaiiUSdiYCXR5E',
                 'TTbKRT4kqbSDDSXL2VSE9hvzPoisvKnBoRSz',
                 'TTbKRT4mcFGWvCgMwprNVCifkNwgGP7Q2UAv',
                 'TTbKRT4mdzsc9dbvMS8N8UUJTCsoxCZTQGue',
                 'TTbKRT4mEF6eWHwxUYKaB7qQPuLTGvxWaM6A',
                 'TTbKRT4pgb9hUW4JERiuePBSCZNh8zrVQu5o',
                 'TTbKRT4rL5dnhRJyYz39VcoftcUDBti9Qrni',
                 'TTbKRT4rUxUMvyuBsbfS9PmoHqVJ8EhcRwzD',
                 'TTbKRT4rY7bDtZyciJF7dxgsbFzXw7opRzVx',
                 'TTbKRT4sYGMwUfocG6qywkoZQMV1dsDbj3JM',
                 'TTbKRT4tkrYaRAeQcktSQ5k5voUb35f71feA',
                 'TTbKRT4tTAWzAVbsaUwMGqtJnRm2ww6A9U1H',
                 'TTbKRT4uidQUHXSAtmNayckjF1pXYyx45M89',
                 'TTbKRT4v36STBfA5qA9AHXJfh2i1rtMiN8Xj',
                 'TTbKRT4wBXBY4PDqpv4k2Z6cSMR4Lw8R8KsS',
                 'TTbKRT4wiwW5EyB5MEhwnv5UoqtkPGoBCmeR',
                 'TTbKRT4x17qjDfAZpQwEBNcf7nsccUgs4Vzv',
                 'TTbKRT4xMGnUcezcWAjQkHSFUdjrkgxnKZdX']

    inlist02 = ['TTbKRT4gdnX68zo6NMzt1YoEtcdKUkpdA8SC',
                        'TTbKRT4h2HMcNMRgWgVxAXzWytSjY5ixrhFW',
                        'TTbKRT4hhemTmsv6w9ykeupD6zwu3rC8vpyh',
                        'TTbKRT4iYyndPE7ecCjQKnvaiiUSdiYCXR5E',
                        'TTbKRT4kqbSDDSXL2VSE9hvzPoisvKnBoRSz',
                        'TTbKRT4mcFGWvCgMwprNVCifkNwgGP7Q2UAv',
                        'TTbKRT4mdzsc9dbvMS8N8UUJTCsoxCZTQGue',
                        'TTbKRT4mEF6eWHwxUYKaB7qQPuLTGvxWaM6A',
                        'TTbKRT4pgb9hUW4JERiuePBSCZNh8zrVQu5o',
                        'TTbKRT4rL5dnhRJyYz39VcoftcUDBti9Qrni',
                        'TTbKRT4rUxUMvyuBsbfS9PmoHqVJ8EhcRwzD',
                        'TTbKRT4rY7bDtZyciJF7dxgsbFzXw7opRzVx',
                        'TTbKRT4sYGMwUfocG6qywkoZQMV1dsDbj3JM',
                        'TTbKRT4tkrYaRAeQcktSQ5k5voUb35f71feA',
                        'TTbKRT4tTAWzAVbsaUwMGqtJnRm2ww6A9U1H',
                        'TTbKRT4uidQUHXSAtmNayckjF1pXYyx45M89',
                        'TTbKRT4v36STBfA5qA9AHXJfh2i1rtMiN8Xj',
                        'TTbKRT4wBXBY4PDqpv4k2Z6cSMR4Lw8R8KsS',
                        'TTbKRT4wiwW5EyB5MEhwnv5UoqtkPGoBCmeR',
                        'TTbKRT4x17qjDfAZpQwEBNcf7nsccUgs4Vzv',
                        'TTbKRT4xMGnUcezcWAjQkHSFUdjrkgxnKZdX']

    xferlis2t = ['TTbKRT4taQHeh9XrH7WhzVDu5UM5S2cMEguR',
                'TTbKRT4tXjJHA9dURtPCDRDfgyQrbdhrmxsy',
                'TTbKRT4u1cND3XGYg6F2KxACcg6e3uewwJ2y',
                'TTbKRT4uQxympsoeAZJaadgH8G6CoapZAzG6',
                'TTbKRT4vzTPhYDqdXCCDJuXUKvPNoTjFqXJm',
                'TTbKRT4wkUjLYmWeT4faSPWxYdBGtt41AcM3',
                'TTbKRT4xBpnSBEvVqvbbRRXjPEBAkKnL2XGS',
                'TTbKRT4o2PPpu3xuKLWCbY1Y6mbmNPB6Gxst',
                'TTbKRT4oqYmhia4jG8kbBjGzS5Skx59Q94ej',
                'TTbKRT4vMkq94SLRCZFgRQpQ252SejJQnZrR',
                'TTbKRT4hTEmtvqcsh6KujDc7ndB4Y3TcPkbY',
                'TTbKRT4qYZtALN5vZGHbbNToqTzSTcMJpapL']
